### ISSUE TITLE
v1.1.0:  'My services'-page throws 'Server error'

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-profile#103]
Mar  7 17:31:40 webapp-1 openconext-profile[30101]: request.CRITICAL: Uncaught PHP Exception OpenConext\Profile\Exception\AssertionFailedException: "Consent JSON structure must contain key "name_id_format"" at /apps/programs/openconext/profile/OpenConext-profile-1.1.0/vendor/beberlei/assert/lib/Assert/Assertion.php line 288 {"exception":"[object] (OpenConext\\Profile\\Exception\\AssertionFailedException(code: 26): Consent JSON structure must contain key \"name_id_format\" at /apps/programs/openconext/profile/OpenConext-profile-1.1.0/vendor/beberlei/assert/lib/Assert/Assertion.php:288)"} []

**Comment by thijskh** [comment]
Did you upgrade Engineblock aswell?

**Comment by tvdijen** [comment]
I'm at 5.6.4 now and the release notes state 5.5.5 as a minimum

**Comment by thijskh** [comment]
It works for me with 5.6.4. Needs more investigation…

**Comment by tvdijen** [comment]
I'm pretty sure it relates to this commit;  https://github.com/OpenConext/OpenConext-profile/commit/144b1448cc600a375c10371406165b08f00115d4#diff-9833e78da6b64c0d176ed54c917cc1e9
Not sure why it affects me though...

**Comment by thijskh** [comment]
NameID format is a mandatory field for an SP in both Manage and Serviceregistry. Do you perhaps somehow have an SP without a nameid format?

**Comment by tvdijen** [comment]
It was never mandatory in SR??
Anyway, I've set it on all SP's and it didn't solve the problem

**Comment by jorissteyn** [comment]
> I'm at 5.6.4 now and the release notes state 5.5.5 as a minimum

That's the culprit. We maintain three versions of EngineBlock in parallel, so for version 1.1.0 of profile you need to update to one of the following versions of EngineBlock:

 * EB5.5: 5.5.5
 * EB5.6: 5.6.5
 * EB5.7: any version

**Comment by tvdijen** [comment]
EB 5.6.5 was released a day after I filed this issue :')
Oh well, I guess now that this is clear, this issue can be closed..
