### ISSUE TITLE
Metadata does not contain signing certificate

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-profile#104]
I'd expect it to contain a `<KeyDescriptor use="signing">` with the value of `saml_sp_publickey` (parameters.yml)

**Comment by thijskh** [comment]
Agreed. We do not currently check the authnrequest signatures. but since profile signs its authnrequests, it publish the key (or stop signing the requests).

**Comment by tvdijen** [comment]
@thijskh I think this one would be fixed by stepup-saml-bundle 4.4.0, am I right?
