### ISSUE TITLE
Show roles from OpenConext Invite

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#293]
We want Profile to be the page where you see the information about you within the entire OpenConext platform. For this reason, we want to add the Roles that the user has in OpenConext-invite to Profile.

Details:
1. This must be a feature flag so you can disable it if you do not use Invite in your installation. No query's should be done and the menu/page should not be visible.
1. Add a new tab in the left menu after "Je persoonlijke data", entitled "Je rollen" leading to a new page of that title.
1. Query the [Invite Profile api](https://invite.test2.surfconext.nl/ui/swagger-ui/index.html#/profile-controller/roles) given the `urn:collab:person:...` id of the user.
1. Present the roles in a way similar to the content of https://welcome.test2.surfconext.nl for the user.

**Comment by MKodde** [comment]
@thijskh regarding the available data in the Invite profile GET response:

1. Do you want the link to the landing page of the role the user is invited for? The aforementioned page uses this link to launch the service I suppose? See screenshot.
2. Should I use the `organisationEn/Nl`?
3. Is it possible for an invite to have more than one application? If this is the case, how should I display this on the UI?

![image](https://github.com/user-attachments/assets/b5ccf49e-1032-4b7c-b7b4-df53ccc71a3d)

**Comment by thijskh** [comment]
1. Launch service should indeed link to the landing page provided by the API
2. Yes, please use the format "$nameNl ($organisationNl)" to display both pieces of information in one line.
3. Yes, multi app roles are possible, the blocks are just repeated. So you'd need to loop over the applications in a given result, display the block for each application, and each block has the (same) name and description of the role. Here's an example for the role "Thijs test multiapp" with description "Multi aap" that has three different applications under it:
![screenshot](https://github.com/user-attachments/assets/6d0491d5-83fa-4f09-a41a-20c0626f17bd)
