### ISSUE TITLE
Cookie parameters language cookie not correct

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#47]
Profile sets a `lang` cookie which is a session cookie with the secure and httponly flags on. This conflicts with the global `lang` cookie shared between other OpenConext applications which is valid for now+2 months; and does not have the secure or httponly flags set.

Please change profile's cookie settings to be in line with this (for the `lang` cookie).

**Comment by thijskh** [comment]
![cookie settings; the first one is 'correct'](https://cloud.githubusercontent.com/assets/3808792/15925539/dbb4d380-2e37-11e6-88f0-a3c57d68cf7e.png)

**Comment by arothuis** [comment]
This has been made configurable in #50
