### ISSUE TITLE
Authentication loop if session cannot be written

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#53]
If for some reason the session cannot be created at login, a new authentication request is triggered, which leads to an authentication loop.

Example of an error that created this situation:

```
Aug 15 15:08:30 papp1 Apache-PROFILE: [Mon Aug 15 15:08:30.031546 2016] [proxy_fcgi:error] [pid 16046] [client 145.101.112.195:51028] AH01071: Got error 'PHP message: PHP Warning:  SessionHandler::read(): open(/var/lib/openconext/session//profile/sess_f,EYaClZgSn1VMW-kY0Bxzbaz87, O_RDWR) failed: Permission denied (13) in /opt/openconext/OpenConext-profile-0.3.0/app/cache/prod/classes.php on line 417\nPHP message: PHP Warning:  SessionHandler::write(): open(/var/lib/openconext/session//profile/sess_f,EYaClZgSn1VMW-kY0Bxzbaz87, O_RDWR) failed: Permission denied (13) in /opt/openconext/OpenConext-profile-0.3.0/app/cache/prod/classes.php on line 421\n', referer: https://engine.surfconext.nl/authentication/sp/consume-assertion
```

Profile should probably show an internal server error in this case, instead of triggering a new authentication request to the IdP.

**Comment by arothuis** [comment]
Whether the session can be written is something that cannot be determined by Profile in PHP. Perhaps this can be fixed during deployment or using an infrastructural tool like heartbeats?

**Comment by thijskh** [comment]
Indeed "should not happen", but when it happens it's less than ideal to have an endless redirect loop as the result instead of a clear error message. If this is complicated to determine we can keep it like this for now.

**Comment by thijskh** [comment]
Closing this since we did not encounter this anymore at any time.
