### ISSUE TITLE
Layout issue in IE11

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#56]
![profile](https://cloud.githubusercontent.com/assets/3808792/18547696/0c90d526-7b45-11e6-8515-a6c159324c7b.png)

**Comment by arothuis** [comment]
I cannot reproduce this on Windows 7 + IE 11 (through BrowserStack).
<img width="1431" alt="screen shot 2016-10-18 at 13 53 14" src="https://cloud.githubusercontent.com/assets/3816591/19476594/49123c60-953a-11e6-9237-139c6c9c4cdc.png">

Can you make sure the page is not visited through some kind of quirks mode / compatibility view?

**Comment by thijskh** [comment]
@tvdijen, can you provide more info?

**Comment by tvdijen** [comment]
It was indeed a case of enabled 'Compatibility View'.
Some beloved (uche-uche) co-worker thought it was a good idea to add a complete TLD to the CV-list..
Thanks @arothuis, for the hint!
