### ISSUE TITLE
Add some links to texts

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#58]
@arnoutt writes:
- Onder My Profile heb ik een link in de tekst opgenomen, graag omzetten naar link
- Onder My Profile staat dat de gebruiker z'n instelling moet mailen, hier moet dan ook het support contact van z'n IdP worden getoond
- Onder My Profile staat 'please refer to the 'My Services' tab.'. Daar ook graag linken naar My Services.

**Comment by arothuis** [comment]
I'd rather not allow raw HTML in translations as one would get too much control over HTML and JavaScript (with the potential for XSS). One solution would be to offer custom tags like old-school forums used to have (bbcode), i.e: `[url]http://www.example.com[/url]` and `[url="http://www.example.com"]A link[/url]`. We could implement this in a our own Twig function and make it extensible by abstracting the replacement strategies. Alternatively, we could look for and use a `bbcode` or `markdown` (or whatever) Twig extension.

Thoughts, @DRvanR?

**Comment by arothuis** [comment]
Discussed in IRL: We should use a Twig sandbox in which certain HTML attributes are whitelisted.

**Comment by arnoutt** [comment]
Sounds good to me!

**Comment by arothuis** [comment]
@arnoutt, what do you mean by "Onder My Profile staat dat de gebruiker z'n instelling moet mailen, hier moet dan ook het support contact van z'n IdP worden getoond".

At the moment, the users' support contact information [is displayed already] (https://github.com/OpenConext/OpenConext-profile/blob/develop/src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig#L13-L16). Should something be changed here?

**Comment by arothuis** [comment]
Bar previous question, this has been implemented in #66.

**Comment by arnoutt** [comment]
I see, it looks like the entire sentence is not shown when the contact data is not known.

I prefer though to always show the entire sentence, and if no contact information is known change the text to:

[EN] If you have any questions about your personal data, please contact the help desk of your institution.
[NL] Heb je vragen over je persoonsgegevens? Neem dan contact op met de helpdesk van je instelling.

**Comment by arothuis** [comment]
Thanks. Will add the message for when a support contact is missing.

**Comment by arothuis** [comment]
Implemented in #66 and #67.
